app:
    resource: '@AppBundle/Controller/Front'
    type: annotation

admin:
    resource: '@AppBundle/Controller/Back'
    type: annotation
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"