language: php
php: 
  - "7.1"
  - "7.0"

before_script:
  - php -v
  - composer install
  - docker run --rm -v $(pwd):/app phpqa/phpcs .
  - docker run --rm -v $(pwd):/app phpqa/security-check security:check

notifications:
  email:
    recipients:
      - haasmyriam8@gmail.com
    on_success: change
    on_failure: always

deploy : 
  provider : heroku
  api_key : 
    secure : "ae904331-4afa-48d3-b960-c7ac0497b16b"