app:
    resource: '@AppBundle/Controller/Front'
    type: annotation

admin:
    resource: '@AppBundle/Controller/Back'
    type: annotation
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_edit:
    path:     /profile/edit
    defaults: { _controller: 'FOSUserBundle:Profile:edit' }

fos_user_profile_show:
     path:     /profile
     defaults: { _controller: 'AppBundle:Front\User:show' }

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"